platform: linux
      
image_resource:
  type: docker-image		
  source: 
    repository: ubuntu
  
inputs: 
- name: api-earthquake

outputs: 
- name: built-project

run:
  path: sh
  args:
   - -exc
   - |
     pwd
     cd api-earthquake
     ./gradlew assemble
     cp ./build/api-earthquake-1.0-SNAPSHOT.jar ../built-project/demo.jar