platform: linux
      
image_resource:
  type: docker-image		
  source: 
    repository: maven
  
inputs: 
- name: api-earthquake

outputs: 
- name: built-project

run:
  path: sh
  args:
   - -exc
   - |
     pwd
     cd api-earthquake
     chmod +x gradlew
     ./gradlew assemble
     cp ./build/libs/api-earthquake-1.0-SNAPSHOT.jar ../built-project/demo.jar
     cp ./build/libs/api-earthquake-1.0-SNAPSHOT.jar ./
     git config --global user.email "shoaib2ali@gmail.com"
     git config --global user.name "techwizblog"
     git add .
     git commit -m "Bumped date"
params:
  TERM: -dumb
  GRADLE_OPTS: -Dorg.gradle.native=false