resources:
  - name: api-earthquake
    type: git
    source:
      uri: https://github.com/techwizblog/api-earthquake.git
      branch: master
      username: techwizblog
      password : {{git-password}}
  - name: release
    type: github-release
    source:
      user: techwizblog
      repository: api-earthquake
  - name: resource-deploy-web-app
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: {{username}}
      password: {{password}}
      organization: suncorp
      space: pws-demo
  - name: resource-deploy-web-app-sys
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: {{username}}
      password: {{password}}
      organization: suncorp
      space: pws-demo

jobs:
 - name: api-earthquake-test-build
   serial: true	
   plan:
    - {get: api-earthquake, trigger: true}
    - get: release
    - task: test
      file: api-earthquake/build-test-ver-2.yml
    - task: build
      file: api-earthquake/build.yml
      
 - name: deploy-dev
   serial: true
   plan:
    - get: api-earthquake
      passed: [api-earthquake-test-build]
      trigger: true
    - get: release      
      trigger: true
    - put: resource-deploy-web-app
      params:
       manifest: api-earthquake/manifest.yml
       path: release/api-earthquake-1.0-SNAPSHOT.jar