resources:
  - name: api-earthquake
    type: git
    source:
      uri: https://github.com/techwizblog/api-earthquake.git
      branch: master

jobs:
- name: api-earthquake-ci
  serial: true	
  plan:
  - {get: api-earthquake, trigger: true}
  - task: build
    privileged: true
    file: api-earthquake/build.yml

jobs:
- name: api-earthquake-test
  serial: true	
  plan:
  - {get: api-earthquake, trigger: true}
  - task: test
    privileged: true
    file: api-earthquake/build.yml
	