resources:
  - name: api-earthquake
    type: git
    source:
      uri: https://github.com/techwizblog/api-earthquake.git
      branch: master
  - name: resource-deploy-web-app
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: {{username}}
      password: {{password}}
      organization: suncorp
      space: pws-demo
  - name: resource-deploy-web-app-sys
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: {{username}}
      password: {{password}}
      organization: suncorp
      space: pws-demo

jobs:
- name: api-earthquake-ci
  serial: true	
  plan:
  - {get: api-earthquake, trigger: true}
  - task: build
    privileged: true
    file: api-earthquake/build.yml
- name: api-earthquake-test
  serial: true	
  plan:
  - get: api-earthquake
    passed: [api-earthquake-ci]
    trigger: true
  - task: test
    privileged: true    
    file: api-earthquake/build-test.yml

- name: api-earthquake-dev
  serial: true	
  plan:
  - get: api-earthquake
    passed: [api-earthquake-test]
    trigger: true
  - task: test
    privileged: true    
    file: api-earthquake/build.yml
  - put: resource-deploy-web-app
    params:
      manifest: api-earthquake/manifest.yml
      path: built-project/demo.jar
  - put: resource-deploy-web-app-sys
    params:
      manifest: api-earthquake/manifest.yml
      path: built-project/demo.jar
