resources:
  - name: api-earthquake
    type: git
    source:
      uri: https://github.com/techwizblog/api-earthquake.git
      branch: master
  - name: release
    type: git
    source:
      branch: master
      uri: https://gist.github.com/7fb2416656a9ee4134de06a32994fec1.git
  - name: resource-deploy-web-app
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: {{username}}
      password: {{password}}
      organization: suncorp
      space: pws-demo
  - name: resource-deploy-web-app-sys
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: {{username}}
      password: {{password}}
      organization: suncorp
      space: pws-demo

jobs:
- name: api-earthquake-ci
  serial: true	
  plan:
  - {get: api-earthquake, trigger: true}
  - get: release
  - task: build
    privileged: true
    file: api-earthquake/build.yml
  - task: test
    privileged: true
    file: api-earthquake/build-test-ver-2.yml
  - put: release
    params: {repository: release}
  - put: gh-release
    params:
     name: ../built-project/demo.txt
     tag: ../built-project/tag.txt
     globs: 
      - built-project/*.jar